### ISSUE TITLE
Adding more pose in dataset

### ISSUE THREAD

**Issue by VennyHong** [bourbonbourbon/yoga-pose-detection-correction#1]
Help me to add more pose images in dataset

**Comment by bourbonbourbon** [comment]
I have added `create_poses_csv.ipynb` and `create_angles_csv.ipynb` in the latest commit. So, **perform a pull**. The images should be preferably JPG/JPEG. And the image names should be [number].jpg preferably.
1. Create a new directory in `./poses_dataset/Images` (the name can be anything but I recommend to use the name of the pose) and populate the it with the pose images.
2. Create another directory in `./poses_dataset/angles` (again the name can be anything) and put one image of the pose. The image in this directory will be used as a 'known good' pose angles (the pose should be perfect), as in, during live detection the user's pose will be compared against this pose to make recommendations.
3. Run `create_poses_csv.ipynb` in the virtual env. This will create a file named https://github.com/bourbonbourbon/yoga-pose-detection-correction/blob/eef0d39bb4086581300aa4ae97d3592284b973d8/create_poses_csv.ipynb#L166 (you can name it whatever) which has all the x, y, z, and visibility values of all the desired landmark points of all poses in the `./poses_dataset/Images` directory. The pose column value in the generated csv file will be an integer btw.
4. Then run `create_angles_csv.ipynb`. It will use the csv generated in the previous step https://github.com/bourbonbourbon/yoga-pose-detection-correction/blob/eef0d39bb4086581300aa4ae97d3592284b973d8/create_angles_csv.ipynb#L60 This will create another csv named https://github.com/bourbonbourbon/yoga-pose-detection-correction/blob/0658985e1ecedffb0c6fe5fe6875c95f0dc4e8dd/create_angles_csv.ipynb#L58 It will have the 'known good' pose angles. You will have to change the value in the range based on the number of poses that you have (the better way would be to check the number of directories in `./poses_dataset/angles`) https://github.com/bourbonbourbon/yoga-pose-detection-correction/blob/0658985e1ecedffb0c6fe5fe6875c95f0dc4e8dd/create_angles_csv.ipynb#L62
5. Then run `rfc_model.ipynb` which uses the csv generated in the step 3 as the input file to train/test the data on. It will then create a `.model` file named https://github.com/bourbonbourbon/yoga-pose-detection-correction/blob/0658985e1ecedffb0c6fe5fe6875c95f0dc4e8dd/rfc_model.ipynb#L70
6. Finally you will have to change these variables in `live_detection.py` https://github.com/bourbonbourbon/yoga-pose-detection-correction/blob/0658985e1ecedffb0c6fe5fe6875c95f0dc4e8dd/live_detection.py#L106 https://github.com/bourbonbourbon/yoga-pose-detection-correction/blob/0658985e1ecedffb0c6fe5fe6875c95f0dc4e8dd/live_detection.py#L108 to whatever you have created in steps 4 and 5.

**Comment by bourbonbourbon** [comment]
Let me know if something doesn't work
